stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/holidays_events.csv
    - data/raw/oil.csv
    - data/raw/sample_submission.csv
    - data/raw/stores.csv
    - data/raw/test.csv
    - data/raw/train.csv
    - data/raw/transactions.csv
    - src/preprocess.py
    params:
    - preprocess.input.holidays_events
    - preprocess.input.oil
    - preprocess.input.sample_submission
    - preprocess.input.stores
    - preprocess.input.train
    - preprocess.input.transactions
    - preprocess.output.data
    outs:
    - data/processed/data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/data.csv
    - src/train.py
    params:
    - train.save_metrics
    - train.save_rf_path
    - train.input
    - train.save_xgb_path
    outs:
    - model/rf.pkl
    - model/xgb.pkl
    - metrics/metrics.csv
